name: eatery
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.2 < 3.0.0"
dependencies:
  flutter:
    sdk: flutter
  # hive database
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  path: ^1.8.2
  uicons: ^1.0.1
  flutter_bluetooth_basic: ^0.1.7
  flutter_native_splash: ^2.2.19
  cupertino_icons: ^1.0.2
  sqflite: ^2.0.0+3
  intl: ^0.17.0
  file_picker: ^5.2.0+1
  move_to_background: ^1.0.2
  flutter_svg: ^1.1.6
  font_awesome_flutter: ^10.1.0
  battery_info: ^1.0.8
  platform_device_id: ^1.0.1
  encrypt: ^5.0.1
  path_provider: ^2.0.9
  flutter_dropdown: ^1.0.0+hotfix.1
  flutter_switch: ^0.3.2
  image_picker: ^0.8.5+3
  sn_progress_dialog: ^1.0.8
  excel: ^2.0.0-null-safety-3
  flutter_file_dialog: ^3.0.1
  flutter_archive: ^5.0.0
  qrscan: ^0.3.2
  qr_flutter: ^4.0.0
  flutter_share: ^2.0.0
  number_to_words: ^1.0.0
  url_launcher: ^6.1.4
  googleapis: ^11.2.0
  googleapis_auth: ^1.3.1
  json_store: ^2.0.0-nullsafety.0
  flutter_secure_storage: ^8.0.0
  get: ^4.6.5
  date_time_picker: ^2.1.0
  floor: ^1.3.0
  clipboard: ^0.1.3
  http: ^0.13.4
  shared_preferences: ^2.0.15
  currency_picker: ^2.0.11
  permission_handler: ^10.0.0
  lottie: ^2.3.2
  flutter_slidable: ^3.0.0
  devdart_windows_hdsn: ^0.0.2
  # bluetooth esc printer
  bluetooth_thermal_printer:
    path: ../bluetooth_thermal_printer
    # git:
      # url: 'https://github.com/devstroop/bluetooth_thermal_printer.git'
      # ref: 'master'
  # database provider
  eatery_db:
    path: "../eatery_db"
    # git:
      # url: 'https://github.com/devstroop/eatery_db.git'
      # ref: 'main'
  eatery_components:
    path: "../eatery_components"
    # git:
      # url: 'https://github.com/devstroop/eatery_components.git'
      # ref: 'main'
  # (archived) eatery_services:
    # path: "../eatery_services"
    # git:
      # url: 'https://github.com/devstroop/eatery_services.git'
      # ref: 'main'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: any
  hive_generator: ^1.1.3
  build_runner: ^2.2.1
  floor_generator: ^1.3.0
  flutter_lints: ^2.0.1

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icons/icon.png"


flutter:
  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/lottie/
