import 'package:eatery/functions/order.function.dart';
import 'package:eatery/references.dart';
import 'package:get/get.dart';
import 'package:intl/intl.dart';

class OrderPrintPage extends StatefulWidget {
  const OrderPrintPage(
      {super.key,
      required this.order,
      required this.currentCart,
      this.printKOT = false,
      this.printInvoice = false});

  final Order order;
  final List<Product> currentCart;
  final bool printKOT;
  final bool printInvoice;

  @override
  State<OrderPrintPage> createState() => _OrderPrintPageState();
}

class _OrderPrintPageState extends State<OrderPrintPage> {
  final GlobalKey genKey = GlobalKey();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.grey[200],
      body: ListView(
        children: [
          const SizedBox(
            height: 24,
          ),
          const Row(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              Text(
                'KOT Preview',
                style: TextStyle(fontSize: 18, fontWeight: FontWeight.w500),
              ),
            ],
          ),
          const SizedBox(
            height: 12,
          ),
          kotPreview(context),
          const SizedBox(
            height: 24,
          ),
          const Row(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              Text(
                'Invoice Preview',
                style: TextStyle(fontSize: 18, fontWeight: FontWeight.w500),
              )
            ],
          ),
          const SizedBox(
            height: 12,
          ),
          invoicePreview(context),
          const SizedBox(
            height: 24,
          ),
        ],
      ),
      bottomNavigationBar: BottomAppBar(
        color: KColors.white,
        child: Row(
          mainAxisSize: MainAxisSize.min,
          children: [
            PrimaryButton(
              color: KColors.tertiary,
              onPressed: () {
                Navigator.pushAndRemoveUntil(
                  this.context,
                  MaterialPageRoute(
                    builder: (context) => const DashboardPage(),
                  ),
                  (Route<dynamic> route) => false,
                );
              },
              child: const Text('< Back'),
            ),
            const SizedBox(
              width: 6,
            ),
            PrimaryButton(
              color: KColors.primary,
              onPressed: () async {
                // PrintInvoice.printReceipt(
                //         order: widget.order, account: widget.account)
                //     .then((String message) {
                //       showMessageDialog(context, message, MessageType.info);
                // }).onError((error, stackTrace) {
                //   showMessageDialog(context, error.toString(), MessageType.error);
                // });
              },
              child: Icon(
                Icons.print,
                color: KColors.white,
              ),
            ),
            const SizedBox(
              width: 6,
            ),
            PrimaryButton(
              color: KColors.green,
              onPressed: () async {
                // final temp = await AppFileSystem.getShareDir();
                // final path = '$temp/${getRandomString(8)}.png';
                // await File(path).writeAsBytes(await _capturePng());
                // await shareFile(path, 'Invoice #${widget.order['id']}',
                //     'Autogenerated by RestaurantPOS');
                // //await File(path).delete();
              },
              child: Icon(
                Icons.share,
                color: KColors.white,
              ),
            ),
          ],
        ),
      ),
    );
  }

  invoicePreview(BuildContext context) {
    return Container(
        margin: const EdgeInsets.symmetric(horizontal: 12),
        padding: const EdgeInsets.all(12),
        decoration: BoxDecoration(
            borderRadius: const BorderRadius.all(Radius.circular(12)),
            color: const Color(0xFFFFFFFF),
            border: Border.all(color: const Color(0xFFF0F0F0), width: 1)),
        child: Column(children: [
          Column(
            mainAxisSize: MainAxisSize.min,
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              Text(
                '${Common.company?.name ?? ''} (Invoice)',
                style:
                    const TextStyle(fontSize: 18, fontWeight: FontWeight.bold),
              ),
              Text(
                Common.company?.address ?? '',
                style:
                    const TextStyle(fontSize: 14, fontWeight: FontWeight.w400),
              ),
              Text(
                [Common.company?.email ?? '', Common.company?.phone ?? '']
                    .join(', '),
                style:
                    const TextStyle(fontSize: 14, fontWeight: FontWeight.w400),
              ),
            ],
          ),
          const SizedBox(
            height: 12.0,
            child: Divider(),
          ),
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              Text(
                'Order: #${widget.order.id}',
                style:
                    const TextStyle(fontSize: 14, fontWeight: FontWeight.w400),
              ),
              Text(
                'Date: ${DateFormat('dd/MM/yyyy').format(widget.order.timestamp)}',
                style:
                    const TextStyle(fontSize: 14, fontWeight: FontWeight.w400),
              )
            ],
          ),
          const SizedBox(
            height: 12.0,
            child: Divider(),
          ),
          Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Row(
                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                children: [
                  Text(
                    widget.order.customer?.name ?? '',
                    style: const TextStyle(
                        fontSize: 12, fontWeight: FontWeight.w500),
                  ),
                  Text(
                    widget.order.customer?.phone ?? '',
                    style: const TextStyle(
                        fontSize: 12, fontWeight: FontWeight.w500),
                  ),
                ],
              ),
              Row(
                children: [
                  const Text(
                    'Address: ',
                    style: TextStyle(fontSize: 12, fontWeight: FontWeight.w400),
                  ),
                  Text(
                    widget.order.customer?.address ?? '',
                    style: const TextStyle(
                        fontSize: 12, fontWeight: FontWeight.w500),
                  ),
                ],
              ),
            ],
          ),
          const SizedBox(
            height: 12.0,
            child: Divider(),
          ),
          ListView.builder(
            shrinkWrap: true,
            itemCount:
                widget.order.products.map((obj) => obj.id).toSet().length,
            itemBuilder: (context, index) {
              var productId = widget.order.products
                  .map((obj) => obj.id)
                  .toSet()
                  .toList()[index];

              // Use firstWhere instead of singleWhere
              var product = widget.order.products
                  .firstWhere((element) => element.id == productId);

              return Row(
                children: [
                  Expanded(
                    flex: 4,
                    child: Text(
                      product.name,
                      style: const TextStyle(
                          fontSize: 12, fontWeight: FontWeight.w400),
                    ),
                  ),
                  Expanded(
                    flex: 1,
                    child: Text(
                      'x ${widget.order.products.where((element) => element.id == product.id).length}',
                      style: const TextStyle(
                          fontSize: 12, fontWeight: FontWeight.w400),
                    ),
                  ),
                  Expanded(
                    flex: 2,
                    child: Text(
                      '${OrderFunction.calculateProductPriceWithoutTax(product).toPrecision(2)}/-',
                      style: const TextStyle(
                          fontSize: 12, fontWeight: FontWeight.w400),
                    ),
                  ),
                  Expanded(
                    flex: 3,
                    child: Align(
                      alignment: Alignment.centerRight,
                      child: Text(
                        '${Common.currency?.symbol ?? ''}${OrderFunction.calculateProductSubtotalInCartWithoutTax(widget.order.products, product).toPrecision(2)}',
                        style: const TextStyle(
                            fontSize: 12, fontWeight: FontWeight.w400),
                      ),
                    ),
                  ),
                ],
              );
            },
          ),
          const SizedBox(
            height: 12.0,
            child: Divider(),
          ),
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              const Text(
                'Subtotal',
                style: TextStyle(fontSize: 12, fontWeight: FontWeight.w400),
              ),
              Text(
                '${Common.currency?.symbol ?? ''}${OrderFunction.calculateCartTotalWithoutTax(widget.order.products).toPrecision(2)}',
                style:
                    const TextStyle(fontSize: 12, fontWeight: FontWeight.w400),
              )
            ],
          ),
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              const Text(
                'Tax',
                style: TextStyle(fontSize: 12, fontWeight: FontWeight.w400),
              ),
              Text(
                '${Common.currency?.symbol ?? ''}${(OrderFunction.calculateTotalWithTax(widget.order.products) - OrderFunction.calculateCartTotalWithoutTax(widget.order.products)).toPrecision(2)}',
                style:
                    const TextStyle(fontSize: 12, fontWeight: FontWeight.w400),
              )
            ],
          ),
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              const Text(
                'Total',
                style: TextStyle(fontSize: 12, fontWeight: FontWeight.w400),
              ),
              Text(
                '${Common.currency?.symbol ?? ''}${OrderFunction.calculateTotalWithTax(widget.order.products).toPrecision(2)}',
                style:
                    const TextStyle(fontSize: 12, fontWeight: FontWeight.w400),
              )
            ],
          ),
          const SizedBox(
            height: 12.0,
            child: Divider(),
          ),
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              const Text(
                'Round off (+/-)',
                style: TextStyle(fontSize: 12, fontWeight: FontWeight.w400),
              ),
              Text(
                '${Common.currency?.symbol ?? ''}${widget.order.roundOff.toPrecision(2) ?? '0.00'}',
                style:
                    const TextStyle(fontSize: 12, fontWeight: FontWeight.w400),
              )
            ],
          ),
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              const Text(
                'Grand Total',
                style: TextStyle(fontSize: 16, fontWeight: FontWeight.w400),
              ),
              Text(
                '${Common.currency?.symbol ?? ''}${widget.order.grandTotal.toPrecision(2)}',
                style:
                    const TextStyle(fontSize: 16, fontWeight: FontWeight.bold),
              )
            ],
          ),
        ]));
  }

  kotPreview(BuildContext context) {

    return Container(
        margin: const EdgeInsets.symmetric(horizontal: 12),
        padding: const EdgeInsets.all(12),
        decoration: BoxDecoration(
            borderRadius: const BorderRadius.all(Radius.circular(12)),
            color: const Color(0xFFFFFFFF),
            border: Border.all(color: const Color(0xFFF0F0F0), width: 1)),
        child: Column(children: [
          Column(
            mainAxisSize: MainAxisSize.min,
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              Text(
                '${Common.company?.name ?? ''} (KOT)',
                style:
                    const TextStyle(fontSize: 18, fontWeight: FontWeight.bold),
              ),
              Text(
                Common.company?.address ?? '',
                style:
                    const TextStyle(fontSize: 14, fontWeight: FontWeight.w400),
              ),
            ],
          ),
          const SizedBox(
            height: 12.0,
            child: Divider(),
          ),
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              Text(
                'Order: #${widget.order.id}',
                style:
                    const TextStyle(fontSize: 14, fontWeight: FontWeight.w400),
              ),
              Text(
                'Date: ${DateFormat('dd/MM/yyyy').format(widget.order.timestamp)}',
                style:
                    const TextStyle(fontSize: 14, fontWeight: FontWeight.w400),
              )
            ],
          ),
          const SizedBox(
            height: 12.0,
            child: Divider(),
          ),
          Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Row(
                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                children: [
                  Text(
                    widget.order.customer?.name ?? '',
                    style: const TextStyle(
                        fontSize: 12, fontWeight: FontWeight.w500),
                  ),
                  Text(
                    widget.order.customer?.phone ?? '',
                    style: const TextStyle(
                        fontSize: 12, fontWeight: FontWeight.w500),
                  ),
                ],
              ),
              Row(
                children: [
                  const Text(
                    'Address: ',
                    style: TextStyle(fontSize: 12, fontWeight: FontWeight.w400),
                  ),
                  Text(
                    widget.order.customer?.address ?? '',
                    style: const TextStyle(
                        fontSize: 12, fontWeight: FontWeight.w500),
                  ),
                ],
              ),
            ],
          ),
          const SizedBox(
            height: 12.0,
            child: Divider(),
          ),
          ListView.builder(
            shrinkWrap: true,
            itemCount:
            widget.currentCart.map((obj) => obj.id).toSet().length,
            itemBuilder: (context, index) {
              var productId = widget.currentCart
                  .map((obj) => obj.id)
                  .toSet()
                  .toList()[index];

              // Use firstWhere instead of singleWhere
              var product = widget.currentCart
                  .firstWhere((element) => element.id == productId);

              return Row(
                children: [
                  Expanded(
                    flex: 4,
                    child: Text(
                      product.name,
                      style: const TextStyle(
                          fontSize: 12, fontWeight: FontWeight.w400),
                    ),
                  ),
                  Expanded(
                    flex: 1,
                    child: Align(
                      alignment: Alignment.centerRight,
                      child: Text(
                        'x ${widget.currentCart.where((element) => element.id == product.id).length}',
                        style: const TextStyle(
                            fontSize: 12, fontWeight: FontWeight.w400),
                      ),
                    ),
                  ),
                ],
              );
            },
          ),
          const SizedBox(
            height: 12.0,
            child: Divider(),
          ),
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              const Text(
                'Total Qty',
                style: TextStyle(fontSize: 16, fontWeight: FontWeight.w400),
              ),
              Text(
                '${widget.currentCart.length}',
                style:
                    const TextStyle(fontSize: 16, fontWeight: FontWeight.bold),
              )
            ],
          ),
        ]));
  }
}
